### ISSUE TITLE
Configurar para que o logo e banner sejam inseridos via aparência > opções do tema > com Sitio Multidiomas com o plugin Polylang

### ISSUE THREAD

**Issue by marcoslmori** [bireme/bvs-site-wp-plugin#19]
Mesmo comportamento que está ocorrendo com os plugins de noticias e agenda de eventos

https://github.com/bireme/bvs-noticias/issues/8

**Comment by wilsonmoura** [comment]
Resolvido em 8dcc7510cff76508f0b0acf064ae0d9f80454716
