### ISSUE TITLE
Corrigir codificação do output do widget vhl cluster

### ISSUE THREAD

**Issue by marcoslmori** [bireme/bvs-site-wp-plugin#22]
![image](https://cloud.githubusercontent.com/assets/10047460/21681117/e7819af2-d334-11e6-8590-fdb95c2fc64a.png)

**Comment by cordeirofilho** [comment]
Foi identificado que o erro é no rss padrão Wordpress e não no plugin.

**Comment by viniciusandrade** [comment]
Foi resolvido em https://github.com/bireme/iahx-opac/issues/45 alterando-se o template que gera o RSS no sistema de pesquisa IAHX.
