### ISSUE TITLE
Error al instalar con WP 4.8.2

### ISSUE THREAD

**Issue by javoMx** [bireme/bvs-site-wp-plugin#31]
Presento los siguiente al querer activarlo:

Parse error: syntax error, unexpected 'endif' (T_ENDIF) in /home/educcomm/public_html/portal/wp-content/plugins/bvs-site-wp-plugin-master/bvs-widgets/servplat_login_widget.php on line 106
--

1 | 0.0125 | 247424 | {main}( ) | .../plugins.php:0
2 | 1.2340 | 8880312 | plugin_sandbox_scrape( ) | .../plugins.php:164
3 | 1.2345 | 8881440 | include( '/home/educcomm/public_html/portal/wp-content/plugins/bvs-site-wp-plugin-master/bvs-site.php' ) | .../plugin.php:1882
4 | 1.2348 | 8882856 | require_once( '/home/educcomm/public_html/portal/wp-content/plugins/bvs-site-wp-plugin-master/bvs-core/widgets.php' ) | .../bvs-site.php:33

Gracias

**Comment by wilsonmoura** [comment]
@javoMx Cambiamos las tags cortas del PHP. Probablemente esto debe resolver el problema. Por favor, actualice el plugin y vuelva a probar.
