### ISSUE TITLE
Problema na configuração de leitura para o item página de post

### ISSUE THREAD

**Issue by barrosjo** [bireme/bvs-site-wp-plugin#32]
![image](https://user-images.githubusercontent.com/19578003/42115930-70c604a2-7bcb-11e8-976c-3307d34eea6d.png)

Em configurações de leitura, mesmo selecionando página de post ela não assume qualquer página selecionada.

**Comment by marcoslmori** [comment]
Deve ser avaliado uma forma de associar uma página com visualizações dos posts recentes do site de acordo com a configuração acima.

**Comment by cordeirofilho** [comment]
Para essa correção eu proponho um page template que liste todos os últimos posts, assim a página criada com o template iria listar todos os posts.

**Comment by barrosjo** [comment]
A ideia é exatamente essa, inclusive o wp já prevê a opção de selecionar uma página para exibir todos os posts em Aparência > Personalizar > Página Inicial Estática > Página de Post. Porém, a página selecionada não está exibindo os posts criados, mas sim a home da BVS
![image](https://user-images.githubusercontent.com/19578003/44733878-e78bb100-aabe-11e8-8423-cf49bbcdf620.png)
![image](https://user-images.githubusercontent.com/19578003/44733935-0722d980-aabf-11e8-9a5b-3883f092b83a.png)
![image](https://user-images.githubusercontent.com/19578003/44734080-73054200-aabf-11e8-89fa-a918025d6dfa.png)

**Comment by wilsonmoura** [comment]
@barrosjo Esse recurso existe para atender a grande maioria de temas do WordPress focados para a arquitetura de blog. No contexto de blog, a página inicial padrão sempre mostra os últimos posts. Sendo assim, essa configuração nunca vai funcionar no tema do plugin da BVS, pois diferente de um blog, a arquitetura do tema é livre para montar o layout da página principal. A sugestão do @cordeirofilho resolve essa questão, pois será possível visualizar os posts mais recentes em qualquer página. Basta configurar a página escolhendo o respectivo modelo (ver imagem).

![last-post](https://user-images.githubusercontent.com/3779520/44875205-df28a700-ac73-11e8-8c7a-51b0ced1d03d.png)

**Comment by barrosjo** [comment]
Como a BVS não é um blog, como foi muito bem colocado, não deveríamos usar a opção de mostrar "Seus posts recentes" na Página Inicial, como é utilizado atualmente e sim mostrar "Uma página estática". De toda forma, aguardo então o desenvolvimento do novo recurso para que possa ser testado. 

Opção utilizada na BVS atualmente:
![image](https://user-images.githubusercontent.com/19578003/44998042-c75d6580-af88-11e8-93e0-45289befb239.png)

Opção que poderia ser utilizada na BVS: 
![image](https://user-images.githubusercontent.com/19578003/44998067-fecc1200-af88-11e8-8465-50bf4b9d2025.png)

**Comment by wilsonmoura** [comment]
Realizado em https://github.com/bireme/bvs-site-wp-plugin/pull/37

**Comment by wilsonmoura** [comment]
@barrosjo atualizamos o ambiente de testes da BVS Economia da Saúde para que você possa testar e validar o ajuste realizado pelo @cordeirofilho

**Comment by barrosjo** [comment]
Testes realizados. Da forma como está a opção Posts > Categorias > Ver já apresenta os posts por categorias no mesmo formato que o template criado. O que diferencia é que um apresenta os posts por categorias e o outro apresenta todos os posts independente da categoria. Bom, considerando que será uma página para exibir notícias, em ambos os casos é necessário incluir os seguintes campos que poderão ou não ser selecionados para exibição: autor, data, categorias, tags e Leia Mais (no resumo da notícia). Falta também opções de compartilhamento (email, redes sociais, etc.). E breadcrumb Home>Notícias>notíciaxyz. No caso do template criado falta também uma opção para selecionar de qual categoria os posts serão exibidos naquela página, posso por exemplo, criar uma página para exibir os posts de avaliação tecnológica e uma página para exibir os post de economia da saúde.

**Comment by wilsonmoura** [comment]
@barrosjo a página dos posts mais recentes tem o mesmo formato da página de categorias. Os metadados adicionais mencionados e breadcrumb serão implementados na estrutura da página. As opções de compartilhamento necessitam de um plugin já utilizado em algumas BVSs, que deve ser instalado via solicitação encaminhada por OCOMON. No caso de opção para selecionar categoria, já existem as páginas de cada categoria, que são criadas automaticamente pelo WordPress. Basta marcar os posts nas respectivas categorias e acessar o link em `Posts > Categorias > Ver`.
