### ISSUE TITLE
Widget Minha BVS para ser disponibilizado o serviço em outras BVSs

### ISSUE THREAD

**Issue by marcoslmori** [bireme/bvs-site-wp-plugin#33]
Foi analisado a implementação do widget e a primeira avaliação está documentado em:  http://wiki.bireme.org/intranet/index.php/Minhabvs

Como sugestão seria incluir como extensão de opção de tema do plugin da BVS

- Após testes na BVS Brasil identificou-se que a melhor posição para disponibilizar o serviço é no menu. No entanto, não é possível utilizar o widget no menu. Sugere-se então disponibilizar como opções de tema na barra superior ao lado dos idiomas e dos contatos. Espaço dedicado somente para isso como link ou ícone

**Comment by cordeirofilho** [comment]
Alteração feita, os arquivos estão no repositório https://github.com/cordeirofilho/bvs-site-wp-plugin

**Comment by wilsonmoura** [comment]
Ajustes implementados em https://github.com/bireme/bvs-site-wp-plugin/pull/36
