### ISSUE TITLE
widget cluster BVS - Permitir link com filtros no IAHX no campo  IAHX url

### ISSUE THREAD

**Issue by marcoslmori** [bireme/bvs-site-wp-plugin#35]
![image](https://user-images.githubusercontent.com/10047460/43164838-a28cda78-8f68-11e8-94b7-cbf898f86f50.png)

Exemplo: 
http://pesquisa.bvsalud.org/portal/?u_filter%5B%5D=fulltext&u_filter%5B%5D=collection&u_filter%5B%5D=db&u_filter%5B%5D=mj_cluster&u_filter%5B%5D=type_of_study&u_filter%5B%5D=clinical_aspect&u_filter%5B%5D=limit&u_filter%5B%5D=pais_assunto&u_filter%5B%5D=la&u_filter%5B%5D=year_cluster&u_filter%5B%5D=type&u_filter%5B%5D=ta_cluster&u_filter%5B%5D=jd&u_filter%5B%5D=pais_afiliacao&fb=&where=&filter%5Bpais_assunto%5D%5B%5D=paraguay#pais_assunto#pais_assunto#pais_assunto#pais_assunto#pais_assunto

Primeira avaliação:  Aumentar a quantidade de caractere no campo de input text

Ou Analisar se existe algum caractere que quebra o solicitação

**Comment by wilsonmoura** [comment]
Realizado em https://github.com/bireme/bvs-site-wp-plugin/pull/37
