### ISSUE TITLE
Exibir breadcrumb e campos adicionais na página de categorias

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/bvs-site-wp-plugin#38]
Incluir breadcrumb e os seguintes campos para exibição:
- autor
- data
- categorias
- tags
- Leia Mais (no resumo da notícia)

**Comment by cordeirofilho** [comment]
@wilsonmoura 

Por favor veja se esta de acordo 

![screenshot_2018-09-13 bireme 1](https://user-images.githubusercontent.com/460341/45515758-79faa880-b77f-11e8-9b97-fc711e7cc7f4.png)

**Comment by wilsonmoura** [comment]
@cordeirofilho layout aprovado.

**Comment by wilsonmoura** [comment]
Tarefa já realizada.
