### ISSUE TITLE
Exibir breadcrumb e campos adicionais no page template Últimas Notícias

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/bvs-site-wp-plugin#39]
Incluir breadcrumb e os seguintes campos para exibição:
- autor
- data
- categorias
- tags
- Leia Mais (no resumo da notícia)

**Comment by cordeirofilho** [comment]
@wilsonmoura 
Veja se dessa forma esta de acordo 

![screenshot_2018-09-13 bireme](https://user-images.githubusercontent.com/460341/45513985-892b2780-b77a-11e8-8724-5174c93dd3ad.png)

**Comment by wilsonmoura** [comment]
@cordeirofilho layout aprovado.

**Comment by wilsonmoura** [comment]
Tarefa já realizada.
