### ISSUE TITLE
Alinhamento vertical dos ícones dos temas com o seu texto correspondente.[ocomon 6211]

### ISSUE THREAD

**Issue by marcoslmori** [bireme/bvs-site-wp-plugin#45]
- Ajustar o alinhamento vertical dos ícones dos temas com o seu texto correspondente. 
- Avaliar também  aumentar a distância entre um tema e outro

![image](https://user-images.githubusercontent.com/10047460/56062204-0b47f280-5d42-11e9-9c7c-5590fc86827d.png)

**Comment by marcoslmori** [comment]
esse comportamento é do tema do plugin da BVS

**Comment by marcoslmori** [comment]
esse chamado se refere a instancia https://bvsenfermeria.bvsalud.org/pt/

**Comment by marcoslmori** [comment]
a  instancia de teste está com layout diferente https://wp-bvsenfermeria.teste.bvsalud.org/pt/

**Comment by marcoslmori** [comment]
https://wp-bvsenfermeria.homolog.bvsalud.org/ para acesso indicar o ip para o ITI

**Comment by marcioalvessilva** [comment]
Problema não identificado. 
![image](https://user-images.githubusercontent.com/48724136/98120445-b7a17a80-1e8c-11eb-80d8-ac4b32424124.png)
