### ISSUE TITLE
Criar um plugin para implementar a barra de acessibilidade em WordPress 

### ISSUE THREAD

**Issue by marcoslmori** [bireme/bvs-site-wp-plugin#47]
- Um plugin separado do plugin da BVS para que seja implementado em qualquer instancia de wordpress ou  
- Analisar como um recurso a mais do plugin da BVS 
- Configuração: 
  - Campo customizado onde pode indicar as classes ou ids onde o plugin não está resolvendo a acessibilidade 
  - Ativado sempre aparecerá no topo 
- A ideia de implementação já foi feito em outro projeto no tema da Saúde Ambiental   e Economia da Saúde 
- Os plugins dentro da biblioteca do wordpress testados não atende o padrão dentro da orientação do tema da BVS  - posicionamento  no topo especificação do governo 
- Obter o maior número de elementos de um tema de BVS para um padrão de implementação

**Comment by renatomurasaki** [comment]
@renatomurasaki se a análise da equipe é descontinuar o plug-in da BVS (bvs-site), a resposta já está dada: seria um plug-in independente de acessibilidade. Eu sugiro ampliar para ser um plug-in para padronização do header (acessibilidade) e do footer (links para a política de privacidade, termos e condições de uso e informação, informação técnica e informação institucional)

**Comment by marcoslmori** [comment]
Valeu @renatomurasaki.  @wilsonmoura e @marcioalvessilva  ajustar com o Renato a prioridade e os recursos necessários para o desenvolvimento desse plugin.  Abraços,

**Comment by marcoslmori** [comment]
Conforme solicitação, @renatomurasaki depois do projeto da ODS, o @wilsonmoura  e o @marcioalvessilva  pode iniciar esse desenvolvimento?

**Comment by wilsonmoura** [comment]
Plugin desenvolvido e disponível em: https://github.com/bireme/accessibility-wp-plugin
