### ISSUE TITLE
Atualização do tema 

### ISSUE THREAD

**Issue by ajuniorgithub** [bireme/bvs-site-wp-plugin#48]
Solicito a revisão do tema BVS Site em virtude das possíveis vulnerabilidades de segurança, além do mesmo apresentar erros ao ser instalado sob versões mais recentes do PHP. O WordPress exibe o seguinte aviso: "Seu site está executando uma versão insegura do PHP (7.2.34-33+ubuntu22.04.1+deb.sury.org+1), que deve ser atualizado."

**Comment by wilsonmoura** [comment]
@ajuniorgithub fizemos as devidas revisões nesse projeto e o mesmo encontra-se de acordo com as recomendações e boas práticas de manutenção e desenvolvimento.
