### ISSUE TITLE
BVS Controle e Câncer - Erro na atualização do plugin polylang

### ISSUE THREAD

**Issue by marcoslmori** [bireme/bvs-site-wp-plugin#49]
Foi feito a atualizaçao no wordpress com WordPress 6.0.2 com o tema [BVS Controle de Câncer]

Ao atualizar o plugin polylang para a versão Versão 3.2.8, quebra o layout e com o debug ligado informa esse erro 

Fatal error: Uncaught Error: Call to undefined method PLL_Model::get_translations() in /home/apps/bvs.br/wp-controlecancer/htdocs/wp-content/plugins/bvs-site/bvs-widgets/vhl_themes_widget.php:33

**Comment by wilsonmoura** [comment]
@marcoslmori ajustes realizados. Favor validar.
