### ISSUE TITLE
BVS Homeopatia depois da atualização do plugin da BVS tem mensagem de erro mau Funcionamento e acesso aos widgets

### ISSUE THREAD

**Issue by marcoslmori** [bireme/bvs-site-wp-plugin#51]
Eu desabiltei o plugin lis e é possivel acessar os widgets, mas está dando mensagem de mau comportamento, tanta na teste como na produção

"The "vhl_network" block was affected by errors and may not function properly. Check the developer tools for more details."

Veja o processo que utilizei no video abaixo:

https://youtu.be/K3j3dEvhM5U

**Comment by marcoslmori** [comment]
Pode ver @wilsonmoura esse problema?

**Comment by wilsonmoura** [comment]
@marcoslmori o widget VHL Network está apresentando erro porque o serviço usado para montar a lista da rede não está funcionando corretamente. Favor verificar esse serviço com o @viniciusandrade.

Segue exemplo de chamada do serviço usado nesse widget: https://srv.bvsalud.org/bvsnet/rss?bvs=bvsalud.org

No entanto, fiz um ajuste no plugin para que a verificação de erro no uso desse widget seja feita com antecedência. Isso vai resolver a mensagem de erro que estava aparecendo na página que exibe a lista de widgets.

**Comment by marcoslmori** [comment]
Vi que vc o plugin está atualizado em instancia de teste.  Vou solicitar para atualizar na produção.  Obrigado
