### ISSUE TITLE
Compatibilização com PHP 8.2

### ISSUE THREAD

**Issue by ajuniorgithub** [bireme/bvs-site-wp-plugin#52]
Solicito que seja executada a compatibilização do plugin com as versões mais recentes do PHP.
A seguir, as mensagens apresentadas pelo debug do WordPress 6.2 quando o tema BVS 2012 é ativado sobre PHP 8.2.

Deprecated: Creation of dynamic property AIOSEO\Plugin\Lite\Admin\PostSettings::$integrations is deprecated in /dados/sites/bvsmig1.icict.fiocruz.br/wp-content/plugins/all-in-one-seo-pack/app/AIOSEO.php on line 248

Warning: Undefined array key "REDIRECT_URL" in /dados/sites/bvsmig1.icict.fiocruz.br/wp-content/plugins/bvs-site-wp-plugin-master/bvs-widgets/servplat_login_widget.php on line 4

Notice: Function wp_enqueue_script was called incorrectly. Scripts and styles should not be registered or enqueued until the wp_enqueue_scripts, admin_enqueue_scripts, or login_enqueue_scripts hooks. This notice was triggered by the thickbox handle. Please see Debugging in WordPress for more information. (This message was added in version 3.3.0.) in /dados/sites/bvsmig1.icict.fiocruz.br/wp-includes/functions.php on line 5827

Notice: Function wp_enqueue_style was called incorrectly. Scripts and styles should not be registered or enqueued until the wp_enqueue_scripts, admin_enqueue_scripts, or login_enqueue_scripts hooks. This notice was triggered by the thickbox handle. Please see Debugging in WordPress for more information. (This message was added in version 3.3.0.) in /dados/sites/bvsmig1.icict.fiocruz.br/wp-includes/functions.php on line 5827

Notice: Function is_feed was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see Debugging in WordPress for more information. (This message was added in version 3.1.0.) in /dados/sites/bvsmig1.icict.fiocruz.br/wp-includes/functions.php on line 5827

Warning: Trying to access array offset on value of type bool in /dados/sites/bvsmig1.icict.fiocruz.br/wp-content/plugins/fi-multimedia-wp-plugin-master/fi-multimedia.php on line 81

Deprecated: Creation of dynamic property MetaSliderPlugin::$themes is deprecated in /dados/sites/bvsmig1.icict.fiocruz.br/wp-content/plugins/ml-slider/ml-slider.php on line 122

Deprecated: Creation of dynamic property MetaSliderPlugin::$api is deprecated in /dados/sites/bvsmig1.icict.fiocruz.br/wp-content/plugins/ml-slider/ml-slider.php on line 126

Deprecated: Creation of dynamic property MetaSlider_Slideshows::$plugin is deprecated in /dados/sites/bvsmig1.icict.fiocruz.br/wp-content/plugins/ml-slider/admin/slideshows/Slideshows.php on line 36

Deprecated: Creation of dynamic property MetaSlider_Api::$slideshows is deprecated in /dados/sites/bvsmig1.icict.fiocruz.br/wp-content/plugins/ml-slider/admin/routes/api.php on line 33

Deprecated: Creation of dynamic property MetaSlider_Api::$themes is deprecated in /dados/sites/bvsmig1.icict.fiocruz.br/wp-content/plugins/ml-slider/admin/routes/api.php on line 34

Deprecated: Creation of dynamic property MetaSlider_Slideshows::$plugin is deprecated in /dados/sites/bvsmig1.icict.fiocruz.br/wp-content/plugins/ml-slider/admin/slideshows/Slideshows.php on line 36

Deprecated: Creation of dynamic property MetaSliderPlugin::$gutenberg is deprecated in /dados/sites/bvsmig1.icict.fiocruz.br/wp-content/plugins/ml-slider/ml-slider.php on line 134

Deprecated: O método construtor chamado para a classe WP_Widget em ServPlat_Login_Widget está obsoleto desde a versão 4.3.0! Em vez disso, use __construct(). in /dados/sites/bvsmig1.icict.fiocruz.br/wp-includes/functions.php on line 5467

Fatal error: Uncaught ArgumentCountError: Too few arguments to function WP_Widget::__construct(), 0 passed in /dados/sites/bvsmig1.icict.fiocruz.br/wp-includes/class-wp-widget-factory.php on line 62 and at least 2 expected in /dados/sites/bvsmig1.icict.fiocruz.br/wp-includes/class-wp-widget.php:163 Stack trace: #0 /dados/sites/bvsmig1.icict.fiocruz.br/wp-includes/class-wp-widget-factory.php(62): WP_Widget->__construct() #1 /dados/sites/bvsmig1.icict.fiocruz.br/wp-includes/widgets.php(115): WP_Widget_Factory->register() #2 /dados/sites/bvsmig1.icict.fiocruz.br/wp-content/plugins/bvs-site-wp-plugin-master/bvs-core/widgets.php(13): register_widget() #3 /dados/sites/bvsmig1.icict.fiocruz.br/wp-includes/class-wp-hook.php(308): register_vhl_widgets() #4 /dados/sites/bvsmig1.icict.fiocruz.br/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters() #5 /dados/sites/bvsmig1.icict.fiocruz.br/wp-includes/plugin.php(517): WP_Hook->do_action() #6 /dados/sites/bvsmig1.icict.fiocruz.br/wp-includes/widgets.php(1854): do_action() #7 /dados/sites/bvsmig1.icict.fiocruz.br/wp-includes/class-wp-hook.php(308): wp_widgets_init() #8 /dados/sites/bvsmig1.icict.fiocruz.br/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters() #9 /dados/sites/bvsmig1.icict.fiocruz.br/wp-includes/plugin.php(517): WP_Hook->do_action() #10 /dados/sites/bvsmig1.icict.fiocruz.br/wp-settings.php(617): do_action() #11 /dados/sites/bvsmig1.icict.fiocruz.br/wp-config.php(102): require_once('...') #12 /dados/sites/bvsmig1.icict.fiocruz.br/wp-load.php(50): require_once('...') #13 /dados/sites/bvsmig1.icict.fiocruz.br/wp-blog-header.php(13): require_once('...') #14 /dados/sites/bvsmig1.icict.fiocruz.br/index.php(17): require('...') #15 {main} thrown in /dados/sites/bvsmig1.icict.fiocruz.br/wp-includes/class-wp-widget.php on line 163

**Comment by wilsonmoura** [comment]
@ajuniorgithub ajustes realizados. Favor atualizar o plugin e validar.
